#!/usr/bin/env python3
import json
from pathlib import Path

def get_coach_description(name, category):
    """Generate coach-style descriptions based on exercise name and category"""
    
    descriptions = {
        # Warmup exercises
        "Jumping Jacks": "Start standing tall, then jump and spread those legs while throwing your arms overhead! Jump back together and repeat. It's simple, gets your heart pumping, and wakes up your whole body. Let's go!",
        "High Knees": "Run in place, but make it count! Drive those knees up high toward your chest, like you're trying to knee yourself in the face. Keep a steady rhythm and feel your heart rate climb!",
        "Arm Circles": "Stand tall and stretch your arms out like airplane wings. Make smooth circles - start small, then go bigger! Do it forward, then backward. Your shoulders are gonna thank you later!",
        "Butt Kicks": "Jog in place and kick your heels back toward your butt! Quick and snappy. Feel those hamstrings wake up. Don't be lazy with it - really try to tap your glutes!",
        "Mountain Climbers": "Get in that push-up position and start running! Drive your knees toward your chest, one at a time, fast as you can. This one's a full-body burner - core, shoulders, cardio, everything!",
        "Windmill": "Stand wide, arms out in a T. Now hinge at your hips and twist - touch your right hand to your left foot while reaching that left arm to the sky. Switch sides. Feel that rotation through your spine!",
        "Hip Circles": "Stand on one leg (grab the wall if you need balance) and make big circles with your hip. Go clockwise, then counterclockwise. You're literally oiling up those hip joints!",
        "Half Middle Split (HMS Lunges)": "Get those feet wide - real wide! Shift your weight side to side, bending one knee while keeping the other leg straight. Feel that deep stretch in your inner thighs. This is gold for hip mobility!",
        "Walking Pike": "Start in a plank, then walk your hands back toward your feet with straight legs. Feel that hamstring stretch! Then walk your hands back out. It's like doing yoga and getting stronger at the same time.",
        "Core Engagements - Floor": "Lie down, press that lower back into the floor like you're trying to flatten it. Now lift your shoulders and legs a few inches off the ground. Hold it! This is your hollow body - master this and handstands become way easier.",
        "Squats": "Feet shoulder-width, drop that butt back like you're sitting in a chair. Keep your chest up! Drive through your heels to stand. This is THE foundation movement. Own it!",
        "Relevé": "Rise up on your tippy-toes as high as you can! Hold for a second at the top, feel those calves working. This builds ankle strength and stability - super important for handstands!",
        "Half Wood Chopper": "Stand wide, clasp your hands together and swing them diagonally like you're chopping wood. Rotate through your core! This wakes up your obliques and spine rotation.",
        "Hand Kicks": "Walk forward and kick one leg up while reaching your opposite hand toward that foot. It's like a walking hamstring stretch with a coordination challenge. Keep it controlled!",
        "Hamstring Stretch (Lying Down)": "Lie on your back, lift one leg up, and pull it toward your chest. Use your hands or a strap. Breathe into it and feel those hamstrings lengthen. No bouncing - just steady pressure!",
        "Lunge Step (with High Knee)": "Step forward into a lunge, then explode up and drive that back knee high! This combines strength, balance, and a bit of cardio. Power through!",
        "Plank Skiing": "Hold a plank and jump both feet side to side together, like you're skiing down a slope. Keep that core tight! It's harder than it looks - your obliques are gonna feel this!",
        "Deep Plié": "Stand with feet wide, toes turned out. Drop down into a deep squat, keeping your chest lifted. Feel it in those inner thighs and glutes. Dancers do these for a reason - they work!",
        "Half Split Push Outs": "Get in a half-split position and rock your hips forward and back. Dynamic hamstring stretching at its finest. Push out, feel the stretch, come back. Repeat!",
        "Assisted 1-Legged Pike Stretch": "Sit with one leg extended, fold forward over that leg. Reach for your foot. Breathe and sink deeper with each exhale. Your hamstrings might hate you now, but they'll love you later!",
        "Leg Swings (Standing)": "Hold the wall for balance and swing one leg forward and back like a pendulum. Controlled, but with momentum. This opens up your hip flexors and hamstrings dynamically!",
        "Burpee": "Drop down, chest to floor, pop up to plank, jump feet forward, explode up! It's the full-body cardio move everyone loves to hate. But man, does it work!",
        "Rocking Boat": "Sit in a V-shape with legs and upper body off the ground. Now rock back and forth. Your abs are gonna be screaming, but hold that V! Balance and core in one crazy package.",
        "Seated Hip Rotations": "Sit with knees bent, let them drop side to side. Easy, gentle, feels amazing for loosening up your hips and lower back. Perfect after sitting all day!",
        "Runner's Stretch (Active)": "Get in a low lunge and pulse forward and back. Feel that front hip flexor open up. Active stretching is where it's at - movement plus stretch equals gold!",
        "Core Engagements (Tuck)": "From hollow body, pull your knees into your chest tight, then extend back out. Keep that lower back glued to the floor! Advanced core control that'll level up your handstands.",
        "Lateral Leg Swings": "Hold the wall, swing your leg side to side across your body. Hip mobility in the frontal plane - we don't do this enough! Go smooth and controlled.",
        "Trunk Twists": "Hands behind your head, twist your torso side to side. Feel those obliques wake up! Great for spine mobility and getting ready for rotational movements.",
        "Shoulder Rolls": "Roll those shoulders - big circles, forward and back. Simple but effective for loosening up all that shoulder tension. Do it slowly and feel every bit of it!",
        "Ankle Bounces": "Bounce on the balls of your feet, rapid-fire! This preps your calves and ankles for explosive stuff. Think of it as waking up your spring mechanism!",
        "Bear Crawl (Forward)": "Get on all fours, lift those knees, and crawl! Opposite hand and foot move together. It's primal, it's effective, and it fires up everything!",
        "Inchworms": "Bend down, walk your hands out to a plank, then walk your feet back to your hands. Full-body movement that stretches hamstrings and builds shoulder strength. Classic!",
        "Jumping Lunges": "In a lunge? Now JUMP and switch legs in the air! Land soft, explode again. This is high-intensity leg work that'll get your heart racing. Push through the burn!",
        "Side Shuffles": "Get in an athletic stance and shuffle laterally. Stay low! This builds lateral movement patterns that most people neglect. Feel those outer thighs work!",
        "Spinal Waves": "Stand and create a wave through your spine - start at your neck, flow down through your whole back to your tailbone. Feels amazing and mobilizes every vertebra!",
        "Toy Soldiers": "Walk forward and kick straight legs up to touch your opposite hand. High kicks, hamstring stretch, coordination all in one. Keep that standing leg straight too!",
        "World's Greatest Stretch": "Low lunge with a twist and reach - this is THE mobility move! Opens hips, hamstrings, thoracic spine all at once. Do it right and you'll understand why it's called the greatest!",

        # Prehab exercises
        "Cat-Cow Stretch": "On all fours, arch your back like a cat (round it up!), then drop your belly and lift your head like a cow. Flow between them with your breath. Your spine will love you!",
        "Wrist Rotations": "Make circles with your wrists - both directions! Seems simple but it's crucial prep for putting weight on your hands. Don't skip this!",
        "Elbow Lifts": "Lie face down, hands behind your head. Squeeze your shoulder blades together and lift those elbows off the ground. Feels great and builds upper back strength!",
        "Forehead to W": "Face down, arms overhead, lift them up and pull back into a W shape. Squeeze those shoulder blades! This is pure scapular control gold.",
        "Back Extensions": "Lie face down and lift your chest off the ground. Keep your hips down! This strengthens your lower back - super important for handstand balance.",
        "Hip Bridges": "Lie on your back, knees bent, lift those hips up! Squeeze your glutes hard at the top. This is THE glute activation move. Don't just go through the motions!",
        "Hip Bridges (with 1 leg)": "Same bridge, but extend one leg. Now you're working one side at a time - way harder! Balance and glute strength combined.",
        "Open & Close Wrists": "Make a tight fist, then spread your fingers wide like you're showing off jazz hands. Repeat! Simple wrist warm-up that prevents injury.",
        "Prayer Pose": "Press your palms together in front of your chest, then push them down while keeping palms together. Feel that wrist flexor stretch! Essential for handstand prep.",
        "Prayer Pose (Reverse)": "Now flip it - press the backs of your hands together with fingers pointing down. Push up! Stretches those wrist extensors. Both sides need love!",
        "Straight to W": "Face down, arms straight overhead, lift and pull them back into a W. You're building shoulder and upper back strength while improving control. Pure gold!",
        "Prone Y's": "Lie face down, make a Y with your arms overhead, lift them up. Keep your neck neutral! This targets those lower traps that keep your shoulders healthy.",
        "Superman": "Lie face down, lift everything - arms, chest, legs! Hold it! You're Superman flying through the air. Great for your entire posterior chain.",
        "Wrist Mobilization": "Make circles with your wrists, both directions. Or do it with hands in prayer position. Get that synovial fluid flowing!",
        "Y-T-W": "Face down, move your arms through Y position, then T, then W - all while lifted off the ground. Advanced upper back control that'll bulletproof your shoulders!",
        "Leg Lifts (Together & Separate)": "Face down, lift both legs together, then alternate lifting them one at a time. Glutes and lower back getting stronger with every rep!",
        "Up & Down Waving": "On all fours, rock your weight forward and back over your wrists in a wave motion. Builds wrist strength and gets them ready for load!",
        "Side Waving": "On all fours, rock side to side over your wrists. Your wrists need to be strong in all directions for handstands. This is how you build it!",
        "Wrist Walks": "Hands and knees, walk your hands in small circles. Hit all angles! Your wrists are getting mobile AND strong.",
        "Finger Stretch": "Gently press each finger back to stretch those finger flexors. Sounds minor but prevents finger strain and keeps your hands happy!",
        "Wrist Mobilization (All Directions)": "Move those wrists through EVERY possible direction - up, down, side to side, circles. Complete wrist prep before loading them up!",
        "Clamshells": "Lie on your side, knees bent, feet together. Lift that top knee up like a clamshell opening. Feel those glutes and hip rotators working! Essential for hip stability.",
        "Quadruped Fire Hydrants": "On all fours, lift one leg out to the side with knee bent. Like a dog at a fire hydrant! Strengthens hip abductors and improves stability.",
        "Ankle Dorsiflexion": "Face a wall, drive your knee forward over your toes. Improves ankle mobility for better squats and landings. Most people need this!",
        "Banded Pull-Aparts": "Hold a band at chest level, pull it apart by squeezing your shoulder blades together. Feel that upper back work! Keeps your shoulders healthy.",
        "Face Pulls (Band)": "Pull that band to your face with elbows high. Absolutely crucial for shoulder health! Your rear delts and upper back will thank you.",
        "External Rotation (Band)": "Elbow at your side at 90 degrees, rotate your forearm out against the band. Strengthens rotator cuff - injury prevention at its finest!",
        "Internal Rotation (Band)": "Same setup, rotate forearm in against resistance. Balance both directions of rotation for healthy shoulders!",
        "Serratus Wall Slides": "Face the wall, hands on it, push yourself away by protracting your shoulder blades. Targets serratus anterior - the handstand muscle!",
        "Towel Scrunches": "Put a towel on the floor, scrunch it toward you with your toes. Strengthens your foot arches and intrinsic muscles. Your feet need training too!",
        "Single Leg Balance": "Stand on one leg and hold it! Seems easy but it builds ankle stability and proprioception. Challenge yourself - close your eyes!",
        "Scapular Retractions": "Squeeze those shoulder blades together, hold, release. The most basic shoulder health exercise. Master this movement pattern!",
        "Prone Swimmers": "Face down, lift opposite arm and leg like you're swimming. Great for posterior chain coordination and strength. Keep it controlled!",
        "Wall Ankle Mobility": "Knee-to-wall drill - see how far from the wall you can get while still touching it with your knee. Progress this distance over time!",
        "Copenhagen Plank": "Side plank with your top leg elevated on a bench. Advanced hip adductor strength! Prevents groin injuries for athletes.",
        "Glute Bridges (Marching)": "In bridge position, alternately lift each foot off the ground. Challenges your glute stability unilaterally. Don't let those hips drop!",

        # Shoulder opener exercises  
        "Wall Slides": "Back against the wall, slide your arms up and down while maintaining contact. Perfect for fixing rounded shoulders and improving posture!",
        "Shoulder Dislocates": "Hold a band or stick wide, rotate it from front to back over your head. Sounds scary, feels amazing! Opens up those shoulders big time.",
        "Band Pull-Aparts": "Hold the band at chest level, pull it apart. Simple, effective, and your shoulders need this daily! Squeeze those shoulder blades!",
        "Shoulder Rotations": "Make big circles with your shoulders - forward and backward. Wake up that rotator cuff and get the blood flowing!",
        "Shoulder Stretch (Standing)": "Pull one arm across your body with the other hand. Hold and feel that shoulder and upper back stretch. Perfect after being at a desk all day!",
        "Handstand Line Builder": "Against the wall, practice that perfect handstand line - wrists, shoulders, hips all stacked. Body awareness is everything! Feel what straight feels like.",
        "Puppy Pose": "On all fours, walk your hands forward and drop your chest toward the ground. Keep hips over knees! Deep shoulder and spine stretch that feels incredible.",
        "Forward Shoulder Stretch": "Clasp hands behind your back, lift them up while bending forward. Opens your chest and anterior shoulders. Breathe into it!",
        "Overhead Shoulder Stretch": "Reach one arm overhead, bend the elbow behind your head, gently pull with the other hand. Stretches triceps and shoulders - hold it!",
        "Behind-the-Back Arm Stretch": "Try to clasp hands behind your back - one arm from above, one from below. Use a strap if you can't reach! Opens shoulders in multiple planes.",
        "Downward Dog": "Make an inverted V with your body - hands and feet on the ground, hips high. Classic yoga pose that opens everything - shoulders, hamstrings, calves!",
        "Shoulder Opener (Elastic Band)": "Hold band wide, pull it over your head and behind you in a slow, controlled arc. Your shoulder flexibility will skyrocket with this!",
        "Shoulder Stretch (Seated, Backwards)": "Sit down, place hands behind you and walk them back. Stretches anterior shoulders and chest while seated. Simple but effective!",
        "Arm Circles (Small, Forward)": "Arms out to sides, make small controlled circles forward. Gentle shoulder warm-up that gets the blood flowing!",
        "Arm Circles (Small, Backward)": "Same thing but backward! Hits different parts of your shoulders. Do both directions!",
        "Arm Circles (Large)": "Now make those circles BIG! Full range of motion. Progress from small to large as you warm up. Your shoulders need this movement!",
        "Pendulum Swings": "Bend forward, let one arm hang, swing it in circles and lines. Classic rehab move for shoulder mobility. Just let gravity do the work!",
        "Thread the Needle": "On all fours, reach one arm under your body and through to the other side. Perfect for thoracic and shoulder rotation! Feel that twist!",
        "Shoulder CARs (Controlled Articular Rotations)": "Slowly move your arm through its full circular range of motion. Every angle, deliberately. This explores and expands your shoulder mobility!",
        "Wall Angels": "Back against wall, arms in goal post position, slide them up and down like making snow angels. Keep everything touching the wall!",
        "Prone I Raises": "Face down, arms overhead in an I shape, lift them slightly. Gentle strengthening for that overhead position!",
        "Prone Y Raises": "Face down, arms in a Y (45 degrees from your head), lift them up. Targets lower traps - crucial for healthy shoulders!",
        "Prone T Raises": "Face down, arms out to sides in a T, lift with thumbs up. Mid-back and posterior shoulder work! Feel that squeeze!",
        "Wall Shoulder Flexion": "Face a wall, walk your fingers up as high as possible. Hold at the top! Gentle active stretch for overhead mobility.",
        "Scapular Wall Slides": "Face the wall, hands on it, push yourself away by moving your shoulder blades. Serratus anterior activation!",
        "Towel Slides": "On a smooth floor, hands on towels, slide them forward and back or out to sides. Low-impact dynamic shoulder mobility!",
        "Cross-Body Arm Swings": "Swing your arms across your body, alternating sides. Dynamic warm-up for shoulders and chest!",
        "Quadruped Shoulder Rotations": "On all fours, rotate one shoulder while keeping your hand planted. Improves rotator cuff mobility with load!",
        "Dynamic Sleeper Stretch": "Lie on your side, elbow bent 90 degrees, pulse your forearm toward the floor. Improves internal rotation!",
        "Book Openers": "Lie on your side, open your top arm like opening a book, follow it with your eyes. Amazing thoracic rotation and shoulder opener!",
        "Reverse Prayer Progression": "Bring hands behind back, press palms together with fingers up. Advanced shoulder mobility - use modifications if needed!",
        "Shoulder Elevation/Depression": "Arms overhead, actively push up then pull down. Building awareness of shoulder blade control!",
        "Doorway Stretch": "Stand in a doorway, hands on the frame, step forward. Classic chest and anterior shoulder opener that never gets old!",
        "Shoulder Pass-Throughs (PVC/Band)": "Hold PVC or band wide, pass it overhead and behind you in a circle. Excellent mobility drill!",
        "Eagle Arms": "Cross arms and wrap forearms, press elbows up. Yoga pose that opens upper back and shoulders. Feels weird, works great!",
        "Cow Face Arms": "One arm overhead bent behind, other behind back bent up, try to clasp hands. Use a strap if needed! Multi-plane shoulder stretch.",

        # Handstand exercises
        "Wall Handstand Hold": "Get upside down against that wall and HOLD IT! Focus on pushing through your shoulders, keep that hollow body tight. This builds the foundational strength!",
        "Handstand Shoulder Taps": "In a wall handstand, carefully tap your shoulders one at a time. Balance challenge on steroids! Your core is working overtime here.",
        "Chest-to-Wall Handstand": "Face the wall, walk up into handstand. Way harder than back-to-wall because it's closer to freestanding. This is next-level balance work!",
        "Handstand Walk (Wall)": "In wall handstand, walk your hands side to side. Builds coordination and strength simultaneously. Feel that shoulder control!",
        "Plank Hold": "Hold that plank - straight body line from head to heels! Shoulders over wrists, core tight. This is your foundation for everything inverted.",
        "Walk To Feet": "From plank, walk your feet toward your hands to create that inverted V. Builds shoulder strength and prepares you for handstand entries!",
        "Walk To Hands": "From the V position, walk your hands toward your feet. Shoulder mobility and strength in the pike position - crucial for press handstands!",
        "Walk To Feet (Elevated)": "Walk feet up onto a box or chair. More challenging because your shoulders are carrying more load. Level up!",
        "Planche Leans": "In plank, shift your weight forward over your hands as far as you can go. This builds crazy straight-arm pressing strength!",
        "Wall Crow": "Squat, hands down, knees on elbows, feet on wall. This is where you learn handstand balance fundamentals. Master this position!",
        "Wall Crow Entries": "Practice getting into Wall Crow over and over. Building that muscle memory and confidence for handstand entries!",
        "Wall Crow Push Outs": "From Wall Crow, push your hips up toward handstand then come back down. This is press-to-handstand training!",
        "Wall Crow (Max Hold)": "Hold Wall Crow as long as you possibly can. Mental toughness and endurance in the inverted position. Push your limits!",
        "Wall Crow (Chair Variation)": "Wall Crow with feet on a chair - increases the shoulder angle and difficulty. Progressive overload in action!",
        "Wall Crow (1-Leg Isolation)": "In Wall Crow, extend one leg at a time. Building unilateral control for freestanding handstands. This is advanced stuff!",
        "Wall Crow (Shoulder Shrugs)": "In Wall Crow, perform shoulder elevation and depression. Advanced scapular control that translates directly to handstand!",
        "Wall Crow (Legs Isolation)": "Lift BOTH legs off your elbows simultaneously. Insane control exercise! This is press-to-handstand territory.",
        "Wall Crow to Handstand": "Press from Wall Crow all the way up to handstand. The ultimate goal! Requires serious shoulder and core strength.",
        "Kick-Up Practice (Wall)": "Practice kicking up to wall handstand. Start gentle, focus on control not power. This is your entry skill!",
        "Kick-Up Drills (Partner Spot)": "Practice kick-ups with a spotter. Build confidence for freestanding attempts. Having that safety net helps!",
        "Handstand Negative (Wall)": "Start in wall handstand, slowly lower down with control. Eccentric strength builder for press handstands. Slow is hard!",
        "Tuck Handstand Negative": "From wall handstand, tuck your knees to chest, slowly lower. Easier than the full version but still challenging!",
        "Straddle Handstand Negative": "Lower down from handstand with legs wide in a straddle. Intermediate press progression. Feel that shoulder burn!",
        "L-Sit (Floor)": "Hands beside hips, press down to lift your entire body with legs extended. Fundamental gymnastics hold that builds crazy strength!",
        "L-Sit (Parallettes)": "L-sit on parallettes or blocks. The extra height makes it easier - great progression step toward the floor version!",
        "Tuck L-Sit": "Pull knees to chest and lift everything off the ground. Beginner L-sit progression that still challenges your core and shoulders!",
        "One-Leg L-Sit": "Lift body with one leg extended, one bent. Easier than full L-sit but still builds the necessary strength!",
        "V-Sit": "Like L-sit but lift those legs higher to make a V. Advanced stuff! Core and hip flexor strength through the roof.",
        "Pike Compression": "Fold forward and hug your legs to your chest. Pull hard! This compression strength is essential for press handstands.",
        "Seated Pike Compression": "Sit with legs extended, lean forward and pull your chest to thighs. Build that pike compression strength sitting down!",
        "Elevated Pike Push-Up": "Feet on a box, pike position, do push-ups. More vertical than regular pike push-ups - mimics the handstand pressing angle!",
        "Headstand Hold": "Balance on your head and forearms. Gentler inversion than handstand but still builds spatial awareness and balance!",
        "Tripod Headstand": "Head and hands form a triangle, knees rest on elbows. Beginner-friendly inversion that builds confidence!",
        "Forearm Stand (Wall)": "Handstand but on your forearms! Lower center of gravity makes balance easier. Great for building confidence upside down!",
        "Straddle Press Attempt": "From pike with legs wide, try to lift hips and legs by leaning shoulders forward. Press handstand progression - keep trying!",
        "Tuck Press Practice": "From squat, lean forward and lift your feet. Tucked press is the easiest press variation. Build toward this!",
        "Press Lean Holds": "From pike, lean shoulders way forward and hold. Builds shoulder strength for press entry without going all the way!",
        "Handstand Hops": "In handstand, do small hops with your hands. Advanced balance and shoulder control! Feel that explosive strength.",
        "Handstand Splits": "In wall handstand, open your legs into splits. Requires hip flexibility and core control. Show off those flexible hips!",
        "Frog Stand": "Squat, hands flat, knees on elbows, lean forward until feet lift. Essential balancing skill! This is where arm balances begin.",
        "Crow Pose": "Like frog stand but lift hips higher and straighten arms more. Classic yoga arm balance. Master this before moving on!",
        "Tuck Planche Lean": "Tuck position on hands, lean forward as far as possible. Straight-arm strength for advanced skills. This is next-level!",
        "Handstand Pirouette Practice": "In handstand, practice small rotations. Advanced skill! Building that rotation control takes time.",
        "Wall Walks": "Start in plank, walk feet up wall while walking hands toward it. Full body strength builder that's harder than it looks!",
        "Handstand Hold (Stomach to Wall)": "Walk up with stomach facing wall. More challenging than back-to-wall - closer to freestanding balance!",

        # Conditioning exercises
        "Plank": "Hold that push-up position! Straight line from head to heels, shoulders over wrists, core TIGHT. Time under tension is everything!",
        "Push-ups": "Classic upper body strength! Lower down with control, push back up. Keep that core tight throughout. Quality over quantity!",
        "Pike Push-ups": "Start in downward dog position, lower your head toward the ground. This mimics handstand push-ups - pure shoulder strength!",
        "Hollow Body Hold": "Lie down, press lower back to floor, lift shoulders and legs. THIS is the secret to handstand balance. Master this shape!",
        "Shoulder Shrugs (Standing)": "Elevate shoulders toward ears, hold, depress. Simple but builds trap strength and shoulder mobility awareness!",
        "Shoulder Shrugs (On Knees)": "On all fours, elevate and depress your shoulders while holding position. Scapular strength for handstands - don't skip this!",
        "Planche Leans": "Plank position, lean shoulders forward past wrists. Hold and return. Straight-arm pressing strength - advanced stuff!",
        "Forearm Planche Leans": "Same thing but on forearms. Slightly easier angle for building strength progressively. Still burns though!",
        "Press Leans": "From pike, lean shoulders way forward over hands. KEY exercise for learning press handstands. Feel that shoulder load!",
        "Scissors (On Back)": "Legs raised, cross them in scissor motion. Lower abs and hip flexors working hard! Keep that lower back pressed down.",
        "Flutter Kicks": "Legs elevated, make small alternating kicks. Lower ab endurance builder. Your core is gonna be on fire!",
        "Abs Twists": "Sit with legs elevated, lean back, twist side to side touching hands to ground. Obliques and rotational strength!",
        "Fire Hydrant": "On all fours, lift leg out to the side. Like a dog at a fire hydrant! Glutes and hip abductors getting stronger.",
        "Knee Extensions": "Sit with one leg bent, lift and extend the knee, lower. Quad strength and knee stability in one!",
        "Toe Taps": "Lie on back, legs in tabletop, slowly tap toes to ground alternating. Core stability exercise that's harder than it looks!",
        "Leg Lifts (One Leg Isolation)": "Face down, lift one leg at a time. Isolates glutes and hamstrings unilaterally. Control is key!",
        "Leg Kicks (Side)": "Stand or lie on side, kick leg out to side. Hip abductors and lateral stability - most people need this!",
        "Leg Kicks (Back)": "Standing, kick one leg straight back. Glute activation and balance combined. Squeeze at the top!",
        "Hollow Body (Wall)": "Lie down, arms overhead against wall, lift shoulders and legs. Advanced hollow body that's way harder! Press that lower back down!",
        "Bicycle Crunches": "Opposite elbow to knee in cycling motion. Classic oblique exercise that works! Keep the movement controlled.",
        "Dead Bug": "On back, extend opposite arm and leg while keeping core engaged. Perfect core stability exercise. Slow and controlled!",
        "Bird Dog": "On all fours, extend opposite arm and leg. Posterior chain and balance! Don't let your hips rotate.",
        "Scapular Push-ups": "In plank, protract and retract shoulder blades without bending elbows. Essential for handstand shoulder strength!",
        "Arch Body Hold": "Face down, lift chest and legs - create that arch! Opposite of hollow body, strengthens the posterior chain.",
        "Wall Sits": "Back against wall, slide down to seated position with thighs parallel. Hold! Leg endurance builder. Embrace the burn!",
        "Reverse Plank": "Sit with legs extended, hands behind, lift hips. Opens chest and strengthens posterior chain. Underrated exercise!",
        "L-Sit Progression": "Sit, hands beside hips, press to lift and extend legs forward. Building toward full L-sit! Keep working at it!",
        "Mountain Climbers (Slow)": "Slow, controlled mountain climbers. More strength, less cardio. Feel every rep working that core!",
        "Side Plank": "Balance on one forearm and side of feet. Obliques and lateral core stability! Hold that straight line.",
        "Side Plank Hip Dips": "In side plank, lower hip toward ground and lift back up. Dynamic oblique work that burns!",
        "Plank to Down Dog": "Flow between plank and downward dog. Dynamic shoulder and core builder. Smooth transitions!",
        "Plank Shoulder Taps": "In plank, tap shoulders with opposite hand. Anti-rotation core exercise. Don't let those hips twist!",
        "Hollow Rocks": "In hollow body, rock back and forth. Advanced gymnastics core exercise. Keep that shape tight!",
        "V-Ups": "Lie flat, lift legs and torso simultaneously to touch toes. Advanced ab exercise! Explosive core power.",
        "Russian Twists": "Sit with feet elevated, twist torso side to side. Obliques and rotational power! Keep that chest up.",
        "Diamond Push-Ups": "Hands in diamond shape, do push-ups. Emphasizes triceps way more than regular push-ups. Feel that burn!",

        # Stretching exercises
        "Wrist Stretch": "Extend arm, gently pull fingers back. Essential for preventing wrist injury! Hold it and breathe.",
        "Shoulder Stretch": "Pull one arm across body. Hold and feel that shoulder stretch. Perfect after being hunched over all day!",
        "Child's Pose": "Sit back on heels, arms extended forward. Total relaxation pose for shoulders and back. Breathe and sink deeper!",
        "Bridge Stretch": "Lie on back, lift hips up high. Great for spine and shoulder flexibility! Push those hips toward the ceiling.",
        "Sphinx (Active)": "Face down, prop on forearms, lift chest. Actively engage your back! Excellent for spine extension.",
        "Sphinx (Passive)": "Same position but relax into the stretch. Let gravity do the work. Breathe and hold!",
        "Cobra (Active)": "From sphinx, straighten arms to lift chest higher. Press into the ground actively! Deeper spinal extension.",
        "Cobra (Passive)": "Hold cobra, relax into it. Focus on breathing deeply. Let that spine open up!",
        "Butterfly (Forward)": "Soles together, fold forward. Hip opener for days! Breathe into those tight hips.",
        "Butterfly (Passive)": "Soles together, let knees drop naturally. Gentle hip opening. Just sit and breathe!",
        "Butterfly (Side)": "From butterfly, lean to one side. Stretches obliques and lateral hip. Feel that side body open!",
        "Wrist Stretch (Reverse)": "Hands flat, fingers pointing back, lean back gently. Essential for computer work and handstand prep!",
        "One Arm Chest Stretch": "Hand on wall, rotate body away. Opens chest and anterior shoulder. Office workers, you need this daily!",
        "Half-Split": "Straighten front leg in lunge, fold forward. Classic hamstring stretch! Keep that back straight.",
        "Half-Split (Side Bend)": "From half-split, reach arm over to side. Adds lateral flexion to hamstring stretch. Double the benefit!",
        "Hip Flexor Stretch": "Kneel on one knee, push hips forward. THE stretch for desk workers with tight hip flexors. Hold it!",
        "Standing Forward Bend": "Fold forward toward toes, let head hang. Entire posterior chain stretch. Let gravity pull you down!",
        "Neck Rolls": "Slowly roll head in circles. Relieves all that desk tension. Move with control!",
        "Neck Side Stretch": "Tilt head to side, gently pull with hand. Lateral neck release. Feels so good!",
        "Upper Trap Stretch": "Tilt head diagonally down, add gentle pressure. Targets those chronically tight upper traps!",
        "Thoracic Extension": "Arch upper back over foam roller or chair. Counteracts that rounded desk posture. Breathe into it!",
        "Cat-Cow": "Alternate between arching and rounding your spine. Classic spinal mobility flow. Move with your breath!",
        "Forearm Stretch (Flexors)": "Arm extended, palm up, pull fingers back. Computer users, this is for you! Hold and breathe.",
        "Forearm Stretch (Extensors)": "Arm extended, palm down, pull fingers down. Both sides of the forearm need stretching!",
        "Finger Stretches": "Spread fingers wide, make fists, pull each finger back. Hand relief for typists and climbers!",
        "Ankle Circles": "Rotate ankles in circles. Improves mobility and circulation. Do both directions!",
        "Toe Stretches": "Interlace fingers between toes and spread. Your feet need love too! Feels weird but amazing.",
        "Seated Spinal Twist": "Sit cross-legged, rotate torso. Spine mobility at its finest! Follow your gaze.",
        "Quad Stretch (Standing)": "Pull foot toward glutes, keep knees together. Classic quad stretch that everyone knows!",
        "Pigeon Pose": "Front leg bent, back leg extended, fold forward. Deep hip opener that office workers desperately need!",
        "Figure Four Stretch": "On back, cross ankle over knee, pull leg toward chest. Targets piriformis and outer hip. Game changer!",
        "Shoulder Blade Squeeze": "Squeeze shoulder blades together and hold. Counters rounded shoulders from desk work!",
        "Triceps Stretch": "Arm overhead, bend elbow, push gently with other hand. Stretches triceps and lat. Hold it!",
        "Lat Stretch (Doorway)": "Hold doorframe overhead, lean away. Deep lat and side body stretch. Feel that lengthening!",
        "Calf Stretch (Wall)": "Hands on wall, step back, keep heel down. Classic calf stretch! Hold and breathe.",
        "IT Band Stretch": "Cross one leg behind other, lean away. IT band and outer hip stretch. Runners need this!",
        "Rag Doll": "Fold forward, grab opposite elbows, hang. Deep relaxing stretch for back and hamstrings. Let it all go!",
        "Lizard Pose": "Low lunge, front foot wider, drop back knee, sink hips. Deep hip flexor and inner thigh opener!",
        "Happy Baby": "On back, grab feet, pull knees toward armpits. Opens hips and lower back. Rock side to side!",
        "Supine Twist": "On back, drop knees to side, keep shoulders flat. Gentle spinal twist. Breathe into it!",
        "Reclined Hamstring Stretch (Strap)": "On back, loop strap around foot, straighten leg up. Gentle hamstring stretch with support. Perfect!",
    }
    
    return descriptions.get(name, "⚠️")

def main():
    vocab_path = Path(__file__).parent / 'data' / 'exercises' / 'vocabulary.json'
    
    with open(vocab_path, 'r') as f:
        data = json.load(f)
    
    updated = 0
    warnings = 0
    
    for exercise in data['exercises']:
        new_desc = get_coach_description(exercise['name'], exercise['category'])
        if new_desc != "⚠️":
            exercise['description'] = new_desc
            updated += 1
            print(f"✅ Updated: {exercise['name']}")
        else:
            exercise['description'] = "⚠️"
            warnings += 1
            print(f"⚠️  Needs research: {exercise['name']}")
    
    # Save updated data
    with open(vocab_path, 'w') as f:
        json.dump(data, f, indent=4)
    
    print(f"\n🎉 Done! Updated {updated} exercises, {warnings} need research.")

if __name__ == '__main__':
    main()